apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-cluster-hackathon
  labels:
    jupyterhub-singluser-service: eje
    radanalytics.io/kind: SparkCluster
data:
  config: >-
    worker:
      instances: 1
      memoryLimit: 1Gi
      memoryRequest: 1Gi
      cpuLimit: 1
      cpuRequest: 500m
    master:
      instances: 1
      memoryLimit: 1Gi
      memoryRequest: 1Gi
      cpuLimit: 1
      cpuRequest: 250m
    customImage:
    docker-registry.default.svc:5000/hackathon/spark-hackathon-2020:latest

    env:

    - name: SPARK_METRICS_ON
      value: prometheus
